---
- name: Provisioning servers
  hosts: all
  become: yes
  roles:
    - role: mypost-install
      vars: 
        ntp0: 0.in.pool.ntp.org
        ntp1: 1.in.pool.ntp.org
        ntp2: mycool.ntp-server.org
